/**
 * curriculum.js — Single source of truth for AI Meme University
 * 
 * ⚠️  AUTO-GENERATED FILE — Do not edit manually!
 * 
 * This file is generated by build_curriculum.py from:
 *   - phase-config.json (phase metadata)
 *   - pdfs/ directory (PDF files)
 * 
 * To update: run `python build_curriculum.py` or push to GitHub.
 * 
 * NAMING CONVENTION FOR PDFs:
 *   pdfs/phase-X/NN-title-words-here.pdf
 *   Example: pdfs/phase-0/01-what-is-ai.pdf
 */

const curriculum = [
    {
        "id": "phase-0",
        "phase": 0,
        "title": "AI Foundations",
        "shortTitle": "Foundations",
        "icon": "🤖",
        "description": "From 'What is AI?' to understanding the landscape of modern artificial intelligence.",
        "memeOnComplete": "Neuron successfully activated 🧠",
        "lessons": [
            {
                "id": 2,
                "title": "History of AI",
                "pdf": "pdfs/phase-0/02-history-of-ai.pdf",
                "description": "History of AI — part of the AI Foundations curriculum.",
                "duration": "12 min"
            },
            {
                "id": 3,
                "title": "AI vs ML vs GENAI",
                "pdf": "pdfs/phase-0/03-ai-vs-ml-vs-genai.pdf",
                "description": "AI vs ML vs GENAI — part of the AI Foundations curriculum.",
                "duration": "12 min"
            }
        ]
    },
    {
        "id": "phase-1",
        "phase": 1,
        "title": "Python for AI",
        "shortTitle": "Python",
        "icon": "🐍",
        "description": "Master the programming language that powers modern AI and machine learning.",
        "memeOnComplete": "print('You are now dangerous') 🐍",
        "lessons": []
    },
    {
        "id": "phase-2",
        "phase": 2,
        "title": "Mathematics for AI",
        "shortTitle": "Mathematics",
        "icon": "📐",
        "description": "The mathematical foundations that power every AI algorithm — linear algebra, calculus, probability, and statistics.",
        "memeOnComplete": "Bro survived backpropagation 💀",
        "lessons": []
    },
    {
        "id": "phase-3",
        "phase": 3,
        "title": "Data Science & Analytics",
        "shortTitle": "Data",
        "icon": "📊",
        "description": "Learn to collect, clean, analyze, and visualize data — the fuel that powers AI.",
        "memeOnComplete": "Data has been wrangled successfully 🤠",
        "lessons": []
    },
    {
        "id": "phase-4",
        "phase": 4,
        "title": "Machine Learning",
        "shortTitle": "Machine Learning",
        "icon": "⚙️",
        "description": "Classical machine learning algorithms — supervised, unsupervised, and everything in between.",
        "memeOnComplete": "Model has been trained. Loss is low. Life is good. 📉",
        "lessons": []
    },
    {
        "id": "phase-5",
        "phase": 5,
        "title": "Deep Learning",
        "shortTitle": "Deep Learning",
        "icon": "🧠",
        "description": "Neural networks, backpropagation, CNNs, RNNs, and the architectures that changed everything.",
        "memeOnComplete": "Your neurons are now fully connected 🧠⚡",
        "lessons": []
    },
    {
        "id": "phase-6",
        "phase": 6,
        "title": "Natural Language Processing",
        "shortTitle": "NLP",
        "icon": "💬",
        "description": "Teaching machines to understand, generate, and process human language.",
        "memeOnComplete": "Language model unlocked 💬🔓",
        "lessons": []
    },
    {
        "id": "phase-7",
        "phase": 7,
        "title": "Transformers",
        "shortTitle": "Transformers",
        "icon": "⚡",
        "description": "The architecture that revolutionized AI — self-attention, BERT, GPT, and the Transformer revolution.",
        "memeOnComplete": "Attention is all you needed 👀",
        "lessons": []
    },
    {
        "id": "phase-8",
        "phase": 8,
        "title": "Generative AI",
        "shortTitle": "GenAI",
        "icon": "✨",
        "description": "Large Language Models, prompt engineering, fine-tuning, and the GenAI revolution.",
        "memeOnComplete": "You can now talk to the machines ✨🤖",
        "lessons": []
    },
    {
        "id": "phase-9",
        "phase": 9,
        "title": "Retrieval-Augmented Generation",
        "shortTitle": "RAG",
        "icon": "🔍",
        "description": "Combining retrieval with generation — vector databases, embeddings, and grounded AI.",
        "memeOnComplete": "Context window expanded successfully 🔍📚",
        "lessons": []
    },
    {
        "id": "phase-10",
        "phase": 10,
        "title": "AI Agents",
        "shortTitle": "Agents",
        "icon": "🤝",
        "description": "Autonomous AI systems that plan, reason, use tools, and take action.",
        "memeOnComplete": "Your agent is now autonomous 🤝🚀",
        "lessons": []
    },
    {
        "id": "phase-11",
        "phase": 11,
        "title": "MLOps & Deployment",
        "shortTitle": "MLOps",
        "icon": "🚀",
        "description": "Taking AI from notebook to production — deployment, monitoring, and ML operations.",
        "memeOnComplete": "Deployed to production without breaking anything 🚀🎉",
        "lessons": []
    },
    {
        "id": "phase-12",
        "phase": 12,
        "title": "AI Safety & Ethics",
        "shortTitle": "AI Safety",
        "icon": "🛡️",
        "description": "Responsible AI — bias, fairness, alignment, interpretability, and the future of safe AI.",
        "memeOnComplete": "AI alignment researcher unlocked 🛡️🧠",
        "lessons": []
    }
];

// Meme messages for various actions
const memeMessages = {
    lessonComplete: [
        "Neuron successfully activated 🧠",
        "One step closer to AGI 🤖",
        "Knowledge gradient: updated ✅",
        "Loss function: decreasing 📉",
        "Training epoch complete 🔄"
    ],
    phaseComplete: [
        "Phase conquered. You're basically Andrej Karpathy now 😎",
        "Weights updated. Moving to the next layer 🧠",
        "Checkpoint saved. No going back now 💾"
    ],
    search: [
        "Cosine similarity search activated 🔍",
        "Retrieving relevant knowledge... 📚"
    ],
    welcome: [
        "Welcome back, fellow learner 🧠",
        "Your neural network missed you 🤖",
        "Resuming training from last checkpoint... 💾"
    ]
};

// ==================== Utility Functions ====================

/** Get total lesson count across all phases */
function getTotalLessons() {
    return curriculum.reduce((total, phase) => total + phase.lessons.length, 0);
}

/** Flatten all lessons into a single ordered list */
function getAllLessons() {
    const lessons = [];
    curriculum.forEach(phase => {
        phase.lessons.forEach(lesson => {
            lessons.push({ ...lesson, phaseId: phase.id, phaseTitle: phase.title, phaseNum: phase.phase });
        });
    });
    return lessons;
}

/** Find a lesson by its global id */
function findLessonById(lessonId) {
    lessonId = parseInt(lessonId);
    for (const phase of curriculum) {
        for (const lesson of phase.lessons) {
            if (lesson.id === lessonId) {
                return { lesson, phase };
            }
        }
    }
    return null;
}

/** Get previous and next lessons for navigation */
function getAdjacentLessons(lessonId) {
    const allLessons = getAllLessons();
    const index = allLessons.findIndex(l => l.id === parseInt(lessonId));
    return {
        prev: index > 0 ? allLessons[index - 1] : null,
        next: index < allLessons.length - 1 ? allLessons[index + 1] : null
    };
}

/** Get phase by id */
function getPhaseById(phaseId) {
    return curriculum.find(p => p.id === phaseId) || null;
}

// Make available globally
if (typeof window !== 'undefined') {
    window.curriculum = curriculum;
    window.memeMessages = memeMessages;
    window.getTotalLessons = getTotalLessons;
    window.getAllLessons = getAllLessons;
    window.findLessonById = findLessonById;
    window.getAdjacentLessons = getAdjacentLessons;
    window.getPhaseById = getPhaseById;
}
